name: svg_maker
description: "Package that helps with svg creation. After creating an svg object user can add elements and modify their attributes."
version: 0.0.1
homepage: https://github.com/nicolabellagamba/svg_maker

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
