part of '../models/svg_element.dart';

enum SvgAttribute {
  // accumulate,
  // additive,
  // alignmentBaseline,
  // amplitude,
  // attributeName,
  // attributeType,
  // azimuth,
  // baseFrequency,
  // baselineShift,
  // begin,
  // bias,
  // by,
  // calcMode,
  // cssClass,
  // clipPath,
  // clipRule,
  // clipPathUnits,
  // color,
  // colorInterpolation,
  // colorInterpolationFilters,
  // cursor,
  cx,
  cy,
  d,
  // //data-*,
  // decoding,
  // diffuseConstant,
  // direction,
  // display,
  // divisor,
  // dominantBaseline,
  // dur,
  // dx,
  // dy,
  // edgeMode,
  // elevation,
  // end,
  // exponent,
  // //fetchpriority,
  fill,
  // fillOpacity,
  // fillRule,
  // filter,
  // filterUnits,
  // floodColor,
  // floodOpacity,
  fontFamily,
  fontSize,
  fontSizeAdjust,
  fontStyle,
  fontVariant,
  fontWeight,
  // fr,
  // from,
  // fx,
  // fy,
  // gradientTransform,
  // gradientUnits,
  height,
  // href,
  // id,
  // imageRendering,
  // in,
  // in2,
  // intercept,
  // k1,
  // k2,
  // k3,
  // k4,
  // kernelMatrix,
  // kernelUnitLength,
  // keyPoints,
  // keySplines,
  // keyTimes,
  // lang,
  // lengthAdjust,
  // letterSpacing,
  // lightingColor,
  // limitingConeAngle,
  // markerEnd,
  // markerMid,
  // markerStart,
  // markerHeight,
  // markerUnits,
  // markerWidth,
  // mask,
  // maskType,
  // maskContentUnits,
  // maskUnits,
  // max,
  // media,
  // method,
  // min,
  // mode,
  // numOctaves,
  // opacity,
  // operator,
  // order,
  // orient,
  // origin,
  // overflow,
  // paintOrder,
  // path,
  pathLength,
  // patternContentUnits,
  // patternTransform,
  // patternUnits,
  // pointerEvents,
  points,
  // pointsAtX,
  // pointsAtY,
  // pointsAtZ,
  // preserveAlpha,
  // preserveAspectRatio,
  // primitiveUnits,
  r,
  // radius,
  // refX,
  // refY,
  // repeatCount,
  // repeatDur,
  // restart,
  // result,
  // rotate,
  rx,
  ry,
  // scale,
  // seed,
  // shapeRendering,
  // //side,
  // slope,
  // spacing,
  // specularConstant,
  // specularExponent,
  // spreadMethod,
  // startOffset,
  // stdDeviation,
  // stitchTiles,
  // stopColor,
  // stopOpacity,
  stroke,
  strokeDasharray,
  strokeDashoffset,
  // strokeLinecap,
  // strokeLinejoin,
  // strokeMiterlimit,
  strokeOpacity,
  strokeWidth,
  style,
  // surfaceScale,
  // crossorigin,
  // systemLanguage,
  // tabindex,
  // tableValues,
  // target,
  // targetX,
  // targetY,
  textAnchor,
  // textDecoration,
  // textRendering,
  // textLength,
  // to,
  // transform,
  // transformOrigin,
  // type,
  // unicodeBidi,
  // values,
  // vectorEffect,
  viewBox,
  // visibility,
  width,
  // wordWpacing,
  // writingMode,
  x,
  x1,
  x2,
  // xChannelSelector,
  xmlns,
  y,
  y1,
  y2;
  // yChannelSelector,
  // z,
  // zoomAndPan,

  String get attribute => 
    switch (this) {
      SvgAttribute.fontFamily => 'font-family',
      SvgAttribute.fontSize => 'font-size',
      SvgAttribute.fontSizeAdjust => 'font-size-adjust',
      SvgAttribute.fontStyle => 'font-style',
      SvgAttribute.fontVariant => 'font-variant',
      SvgAttribute.fontWeight => 'font-weight',
      SvgAttribute.pathLength => 'path-length',
      SvgAttribute.strokeDasharray => 'stroke-dasharray',
      SvgAttribute.strokeDashoffset => 'stroke-dashoffset',
      SvgAttribute.strokeOpacity => 'stroke-opacity',
      SvgAttribute.strokeWidth => 'stroke-width',
      SvgAttribute.textAnchor => 'text-anchor',
      _ => name,
    };
}
